### ISSUE TITLE
Null Reference in load of "big file"

### ISSUE THREAD

**Issue by carlosgs91** [WordDocX/DocX#124]
Hi,

So my code just stopped working after using a "bigger file" of 450 Kb. Nothing else has changed and I cannot load the file anymore as I get a NullReferenceException when I do DocX document = DocX.Load(@"Document.docx")

Exception detail:

System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=DocX
  StackTrace:
       at Novacode.Container.GetListItemType(Paragraph p)
       at Novacode.Container.get_Paragraphs()
       at Novacode.DocX.get_Paragraphs()
       at Novacode.DocX.PostLoad(Package& package)
       at Novacode.DocX.Load(String filename)
       at DocxTesting.Program.ReplaceWithImage() in c:\Users\CAGOM\Documents\Visual Studio 2012\Projects\DocxTesting\DocxTesting\Program.cs:line 23
       at DocxTesting.Program.Main(String[] args) in c:\Users\CAGOM\Documents\Visual Studio 2012\Projects\DocxTesting\DocxTesting\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

Unfortuntely I cannot share the docx document. Is there some limitation in what type of docx the library can open? Perhaps it can't handle documents with review activated?

**Comment by carlosgs91** [comment]
Fixed by removing review
